from typing import Dict, List

# nfl team abbreviations
nfl_team_abbreviations: List[str] = [
    "ARI",
    "ATL",
    "BAL",
    "BUF",
    "CAR",
    "CHI",
    "CIN",
    "CLE",
    "DAL",
    "DEN",
    "DET",
    "GB",
    "HOU",
    "IND",
    "JAX",
    "KC",
    "LAR",
    "LAC",
    "LV",
    "MIA",
    "MIN",
    "NE",
    "NO",
    "NYG",
    "NYJ",
    "PHI",
    "PIT",
    "SEA",
    "SF",
    "TB",
    "TEN",
    "WAS",
]

# reference dict to convert between commonly used alternate team abbreviations
nfl_team_abbreviation_conversions: Dict[str, str] = {"JAC": "JAX", "LA": "LAR", "WSH": "WAS"}

# reference dict to convert between full NFL team names and their abbreviations
nfl_team_names_to_abbreviations: Dict[str, str] = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KC",
    "Los Angeles Rams": "LAR",
    "Los Angeles Chargers": "LAC",
    "Las Vegas Raiders": "LV",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "Seattle Seahawks": "SEA",
    "San Francisco 49ers": "SF",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS",
}

# reference dict to convert between NFL team abbreviations and their full names
nfl_team_abbreviations_to_names: Dict[str, str] = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GB": "Green Bay Packers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "LAR": "Los Angeles Rams",
    "LAC": "Los Angeles Chargers",
    "LV": "Las Vegas Raiders",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NE": "New England Patriots",
    "NO": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "SEA": "Seattle Seahawks",
    "SF": "San Francisco 49ers",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WAS": "Washington Commanders",
}

# prohibited player statuses to check team coaching efficiency eligibility if dq_ce = True
prohibited_statuses: Dict[str, str] = {
    "O": "Out",
    "Out": "Out",
    "NA": "Inactive: Coach's Decision or Not on Roster",
    "INACTIVE": "Inactive: Coach's Decision or Not on Roster",
    "IR-R": "Injured Reserve - Designated for Return",
    "IR": "Injured Reserve",
    "COVID-19": "Reserve: COVID-19",
    "SUSP": "Suspended",
    "Reserve-Sus": "Suspended",
    "DNR": "Reserve: Did Not Report",
    "PUP-P": "Physically Unable to Perform (Preseason)",
    "PUP-R": "Physically Unable to Perform (Regular Season)",
    "NFI": "Non-Football Injury",
    "NFI-A": "Non-Football Injury (Active)",
    "NFI-R": "Non-Football Injury (Reserve)",
    "EX": "Reserve: Exemption",
    "Reserve-Ex": "Reserve: Exemption",
    "CEL": "Reserve: Commissioner Exempt List",
    "Reserve-CEL": "Reserve: Commissioner Exempt List",
    "RET": "Reserve: Retired",
    "Reserve-Ret": "Reserve: Retired",
}

player_name_punctuation: List[str] = [".", "'"]

player_name_suffixes: List[str] = ["Jr", "Sr", "V", "IV", "III", "II", "I"]  # ordered for str.removesuffix support
