# Fantasy Football Metrics Weekly Report - ESPN Configuration

# Essential Settings
log_level: info
league_id: "1271142"
season: 2025
current_nfl_week: 2
refresh_feature_web_data: false  # Set to true to refresh Bad Boy/Beef/High Roller data

# ESPN Authentication (optional - leave empty for public leagues)
platform_settings:
  espn_cookie_swid: ""
  espn_cookie_espn_s2: ""

# Weekly Wager Configuration
weekly_wager_settings:
  enabled: true                     # Set to true to enable weekly wager calculation
  position: ["QB"]            # Position to filter by (QB, RB, WR, TE, K, D/ST) or null for all positions
  filter: "all"                 # Player filter: "starter", "bench", or "all"
  target: "interceptions"                  # Target metric: "points", "touchdowns", "yards", "receptions", "interceptions", "fumbles", "fumbles_lost", "completions", "attempts", "rushing_attempts", "receiving_yards", "rushing_yards"
  direction: "most"                 # Direction: "most" or "least"
  # description: "Starting TE with the most fantasy points"  # Custom description (optional)

